# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

# -- GLOBAL VARIABLES ------------------------------------------------------------------
variables:
  packageFolderName: "isogeotoxlsx"
  pyPiPackageName: "isogeo-export-xl"
  vmImageName: "windows-2019"

# -- STAGES ----------------------------------------------------------------------------
stages:
- stage: Lint
  displayName: Format and lint code

  jobs:
    - job: 'Lint'
      pool:
        vmImage: $(vmImageName)
    
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
          addToPath: true

      - script: |
          python -m pip install -U pip --cache-dir ./.pipcache
          python -m pip install -U -r ./requirements.txt --cache-dir ./.pipcache
        displayName: 'Install dependencies'

      - script: |
          python -m black --target-version=py37 ./$(packageFolderName)
          python -m black --target-version=py37 .\tests
        displayName: 'Apply black code formatting'

      - script: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./$(packageFolderName) --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. Tolerance of line length fixed to 100.
          flake8 ./$(packageFolderName) --count --exit-zero --max-complexity=10 --max-line-length=100
        displayName: "Static code analisis (PEP8 conformance, imports...), using flake8"

        # save formatted code to use later avoiding git clone again
      - publish: $(System.DefaultWorkingDirectory)
        artifact: "FORMATTED_$(pyPiPackageName)_$(Build.SourceBranchName)_$(Build.BuildId)"
        displayName: 'Publish formatted code with dependencies'

- stage: Test
  displayName: Unit tests
  dependsOn: Lint
  condition: succeeded()

  jobs:
  # TESTS
  - job: 'Test'
    pool:
      vmImage: $(vmImageName)
    variables:
      - group: QA

    steps:

    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifact: "FORMATTED_$(pyPiPackageName)_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'
        addToPath: true

    - script: |
        python -m pip install -U pip --cache-dir ./.pipcache
        python -m pip install -U -r ./requirements.txt --cache-dir ./.pipcache
      displayName: 'Install dependencies'

    - script: |
        python .\tests\fixturing.py
        pytest
      env:
        # platform
        ISOGEO_PLATFORM: $(ISOGEO_PLATFORM)
        # URLs
        ISOGEO_API_URL: $(ISOGEO_API_URL)
        ISOGEO_ID_URL: $(ISOGEO_ID_URL)
        # oAuth2 Client Credentials Grant
        ISOGEO_API_GROUP_CLIENT_ID: $(ISOGEO_API_GROUP_CLIENT_ID)
        ISOGEO_API_GROUP_CLIENT_SECRET: $(ISOGEO_API_GROUP_CLIENT_SECRET)
        # static fixtures
        ISOGEO_FIXTURES_METADATA_COMPLETE: $(ISOGEO_FIXTURES_METADATA_COMPLETE)
        ISOGEO_WORKGROUP_TEST_UUID: $(ISOGEO_WORKGROUP_TEST_UUID)
      displayName: 'Tests and coverage - Pytest'

    - task: PublishTestResults@2
      displayName: "Publish unit test results"
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'

    - task: PublishCodeCoverageResults@1
      displayName: "Publish coverage results to Azure Pipelines"
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'


- stage: Deploy
  displayName: Build and Deploy
  dependsOn: Test
  condition: succeeded()

  jobs:
  # BUILD Python package
  - job: 'Build'
    pool:
      vmImage: $(vmImageName)

    steps:
    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifact: "FORMATTED_$(pyPiPackageName)_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        architecture: 'x64'
        addToPath: true

    - script: |
        python -m pip install -U pip --cache-dir ./.pipcache
        python -m pip install -U -r ./requirements.txt --cache-dir ./.pipcache
        python -m pip install -U twine
      displayName: 'Install dependencies'

    - script: python setup.py egg_info
      displayName: 'Build package metadata'

    - script: python setup.py sdist
      displayName: 'Build sdist'

    - script: python setup.py bdist_wheel
      displayName: 'Build wheel'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: Isogeo XLSX Exporter'
      inputs:
        path: $(System.DefaultWorkingDirectory)/dist
        artifact: 'IsogeoToXLSX_$(Build.SourceVersion)'

  # PUBLISH TO GITHUB
  # only with a tagged commit (see: https://github.com/MicrosoftDocs/vsts-docs/issues/3281)
  - job: 'DeployGithub'
    dependsOn: Build
    # only with a tagged commit (see: https://github.com/MicrosoftDocs/vsts-docs/issues/3281)
    condition: |
      and
      (
        succeeded(),
        contains(variables['Build.SourceBranch'], 'tags')
      )
    pool:
      vmImage: $(vmImageName)

    steps:
    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifact: '$(pyPiPackageName)_$(Build.SourceVersion)'
        targetPath: "$(System.DefaultWorkingDirectory)"

    # publish to Github
    - task: GitHubRelease@1
      displayName: "Publish tagged code as Github Release"
      inputs:
        gitHubConnection: 'github_isogeo'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        assets: '$(System.DefaultWorkingDirectory)/*'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'

  # PUBLISH TO the Python Package Index (PyPi)
  # only with a tagged commit (see: https://github.com/MicrosoftDocs/vsts-docs/issues/3281)
  - job: 'DeployPyPi'
    dependsOn: Build
    condition: |
      and
      (
        succeeded(),
        contains(variables['Build.SourceBranch'], 'tags')
      )
    pool:
      vmImage: $(vmImageName)

    steps:
    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifact: '$(pyPiPackageName)_$(Build.SourceVersion)'
        targetPath: "$(System.DefaultWorkingDirectory)/dist/"

    - task: TwineAuthenticate@1
      inputs:
        pythonUploadServiceConnection: 'pypi'

    # see: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-python-upload
    - script: |
        python -m pip install -U pip twine --cache-dir ./.pipcache
        python -m twine upload ./dist/* -r pypi --config-file $(PYPIRC_PATH) --verbose --skip-existing
      continueOnError: true
      displayName: "Upload to PyPi"
