# -*- coding: UTF-8 -*-
#! python3

"""
    Matching table between Isogeo metadata model and Excle columns for Isogeo to Office.
"""

VECTOR_COLUMNS = {
    # model
    "_created": ("AM", "COL_TITLE", "0"),
    "_creator": ("E", "COL_TITLE", "0"),
    "_id": ("AL", "COL_TITLE", "0"),
    "_modified": ("AN", "COL_TITLE", "0"),
    "abstract": ("C", "COL_TITLE", "0"),
    "collectionContext": ("I", "COL_TITLE", "0"),
    "collectionMethod": ("J", "COL_TITLE", "0"),
    "conditions": ("AD", "COL_TITLE", "0"),
    "contacts": ("AF", "COL_TITLE", "0"),
    "coordinateSystem": ("T", "COL_TITLE", "0"),
    "created": ("O", "COL_TITLE", "0"),
    "distance": ("W", "COL_TITLE", "0"),
    "editionProfile": ("", "COL_TITLE", "0"),
    "encoding": ("", "COL_TITLE", "0"),
    "envelope": ("U", "COL_TITLE", "0"),
    "events": ("P", "COL_TITLE", "0"),
    "featureAttributes": ("AA", "COL_TITLE", "0"),
    "features": ("Y", "COL_TITLE", "0"),
    "format": ("S", "COL_TITLE", "0"),
    "formatVersion": ("", "COL_TITLE", "0"),
    "geometry": ("V", "COL_TITLE", "0"),
    "keywords": ("F", "COL_TITLE", "0"),
    "language": ("AO", "COL_TITLE", "0"),
    "layers": ("", "COL_TITLE", "0"),
    "limitations": ("AE", "COL_TITLE", "0"),
    "links": ("", "COL_TITLE", "0"),
    "modified": ("Q", "COL_TITLE", "0"),
    "name": ("B", "COL_TITLE", "0"),
    "operations": ("", "COL_TITLE", "0"),
    "path": ("D", "COL_TITLE", "0"),
    "precisio(n": ("", "COL_TITLE", "0"),
    "published": ("R", "COL_TITLE", "0"),
    "scale": ("X", "COL_TITLE", "0"),
    "series": ("", "COL_TITLE", "0"),
    "serviceLayers": ("", "COL_TITLE", "0"),
    "specifications": ("AB", "COL_TITLE", "0"),
    "tags": ("", "COL_TITLE", "0"),
    "title": ("A", "COL_TITLE", "0"),
    "topologicalConsistency": ("AC", "COL_TITLE", "0"),
    "typ(e": ("", "COL_TITLE", "0"),
    "updateFrequency": ("M", "COL_TITLE", "0"),
    "validFrom": ("K", "COL_TITLE", "0"),
    "validTo": ("L", "COL_TITLE", "0"),
    "validityComment": ("N", "COL_TITLE", "0"),
    # specific,
    "featureAttributesCount": ("Z", "COL_TITLE", "0"),
    "hasLinkDownload": ("AG", "COL_TITLE", "0"),
    "hasLinkOther": ("AI", "COL_TITLE", "0"),
    "hasLinkView": ("AH", "COL_TITLE", "0"),
    "linkEdit": ("AJ", "COL_TITLE", "0"),
    "linkView": ("AK", "COL_TITLE", "0"),
    "inspireConformance": ("H", "COL_TITLE", "0"),
    "inspireThemes": ("G", "COL_TITLE", "0"),
}
